config/routes.rb
Rails.application.routes.draw do
  devise_for :redactors
    resources :destinations do
      resources :ratings
    end  
    root 'destinations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :destinations

end

app/models/destination.rb
class Destination < ApplicationRecord
    belongs_to :redactor
    belongs_to :category
    has_many :ratings
    has_attached_file :destination_img, styles: { destination_index: "300x300>", destination_show: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :destination_img, content_type: /\Aimage\/.*\z/

end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :destination
    belongs_to :redactor
end

app/models/redactor.rb
class Redactor < ApplicationRecord
  has_many :destinations
  has_many :ratings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :find_destination, only: [:show, :edit, :destroy, :update]
    before_action :authenticate_redactor!, only: [:new, :edit]
    
    def index
        if params[:category].blank?
            @destinations = Destination.all.order("created_at DESC")
        else
           @category_id = Category.find_by(name: params[:category]).id
           @destinations = Destination.where(:category_id => @category_id).order("created_at DESC")
        end    
    end    
    
    def show
        if @destination.ratings.blank?
            @average_rating = 0
        else
            @average_rating = @destination.ratings.average(:rating).round(2)
        end    
    end    
    
    def new
        @destination = current_redactor.destinations.build
        @categories = Category.all.map{ |c| [c.name, c.id]}
    end
    
    def create
        @destination = current_redactor.destinations.build(destination_params)
        @destination.category_id = params[:category_id]
                
        if @destination.save
            redirect_to root_path
        else
            render 'new'
        end    
    end
    
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id]}
    end
    
    def update
        @destination.category_id = params[:category_id]
        if @destination.update(destination_params)
            redirect_to destination_path(@destination)
        else
            render 'edit'
        end 
    end
    
    
    def destroy
        @destination.destroy
        redirect_to root_path
    end    
    
    
    private 
    
        def destination_params
           params.require(:destination).permit(:name, :country, :description, :category_id, :destination_img) 
        end    
        
        def find_destination
            @destination = Destination.find(params[:id])        
        end    
    
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    before_action :find_destination
    before_action :find_rating, only: [:edit, :update, :destroy]    
    before_action :authenticate_redactor!, only: [:new, :edit]
    
    def new
        @rating = Rating.new
    end
    
    def create
        @rating = Rating.new(rating_params)
        @rating.destination_id = @destination.id
        @rating.redactor_id = current_redactor.id
        
               
        if @rating.save
            redirect_to destination_path(@destination)
        else
            render 'new'
        end  
    end
    
    def edit

    end    
    
    def update

        if @rating.update(rating_params)
            redirect_to destination_path(@destination)
        else 
            render 'edit'
        end    
    end
    
    def destroy
        @rating.destroy
        redirect_to destination_path(@destination)
    end      
    
    private
    
    def rating_params
       params.require(:rating).permit(:rating, :comment)
    end    
    
    def find_destination
        @destination = Destination.find(params[:destination_id])        
    end   
    
    def find_rating
        @rating = Rating.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/destinations/_form.html.erb
<%= simple_form_for @destination do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
    <%= f.file_field :destination_img %>
    <%= f.input :name, label: "Place Name" %>
    <%= f.input :country %>
    <%= f.input :description %>  
    <%= f.button :submit %>     
<% end %>

app/views/destinations/edit.html.erb
<h1> Edit Trip Advice!</h1>

<%= simple_form_for @destination, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :destination_img %>
    <%= f.input :name, label: "Place Name" %>
    <%= f.input :country %>
    <%= f.input :description %>  
    <%= f.button :submit %>     
<% end %>

app/views/destinations/index.html.erb
<script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<h3 class="current category"><%= params[:category] %></h3>


    <% if @destinations.count == 0 %>
        <h3>Ups! There are no Trip Advices in this category yet.</h3>
        
            <% if redactor_signed_in? %>
                <p><%= link_to "Add New Advice", new_destination_path %> to change this!</p>
            <% else %>
                <p><%= link_to "Log In", new_destination_path %> or <%= link_to "Sign Up", new_redactor_registration_path %> to add the new one!</p>
                 <p></p>
          <% end %>
        
        
    <% else %>
    
    <div class="row">
        <% @destinations.each do |destination| %>
        
            <div class="col-md-3">        
            <a href="/destinations/<%= destination.id %>">
                <%= image_tag destination.destination_img.url(:destination_index), class: "destination-index" %>
                <h4><%= link_to destination.name, destination_path(destination), class: "destination-index" %></h4>            
                
            </a>
            </div>
            



        <% end %> 
        
    </div>    
    
    <% end %>

app/views/destinations/new.html.erb
<h1> New Trip Advice!</h1>

<%= render 'form' %>

app/views/destinations/show.html.erb
<div class="row">
    <div class="col-md-4">


        <%= image_tag @destination.destination_img.url(:destination_show), class: "destination-show" %>
        <h4><%= @destination.country %></h4>
        <h5>Category: <%= @destination.category.name %></h5>
    
    </div> 
    
    <div class="col-md-8">
        <h1><%= @destination.name %></h1>
        <p><%= @destination.description %></p>

        <% if redactor_signed_in? %>
            <% if @destination.redactor_id == current_redactor.id %>
                <%= link_to "Edit", edit_destination_path(@destination) %>
                <%= link_to "Delete", destination_path(@destination), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>    
        <% end %>                
                    
        <%= link_to "Go Back", root_path %>
    
    </div>
    
</div>    


<div class="row">
    <div class="col-md-4">
        
        
        
        <h3>Average Redactor's Rating</h3>    
        <div class="average-rating-rating" data-score=<%= @average_rating %>></div>
        
        <span class="number-of-ratings">Based on <%= @destination.ratings.count %>ratings</span>
        
        <h3>Reviews</h3>
        <%= render @destination.ratings %>
            
        <br>
        <div>
            <% if redactor_signed_in? %>
                <%= link_to "Add Rating", new_destination_rating_path(@destination) %>
            <% else %>
                <p> You should <%=  link_to "Log In", new_redactor_session_path %> or <%= link_to "Sign Up", new_redactor_registration_path %> to have ability to add new rating! </p>
            <% end %>
        </div>
        
    </div>
</div>            
        
        
<script>
	$('.rating-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-rating-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripAdvisor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-default">

      <div class="container">
  
        <div class="navbar-header">
          <%= link_to "Trip Advisor", root_path, class: "navbar-brand" %>
        </div>
  
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_redactor_registration_path %> </li>
              <% if redactor_signed_in? %>
                <li><%= link_to "Sign Out", destroy_redactor_session_path, method: :delete %></li>
              <% else %>
                <li><%=  link_to "Log In", new_redactor_session_path %></li>
              <% end %>
        </ul>
  
        <ul class="nav navbar-nav navbar-right">
          
          <% if redactor_signed_in? %>
            <li><%= link_to "Add New Advice", new_destination_path %></li>
          <% end %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class ="dropdown-menu" role="menu">
                <% Category.all.each do |category| %>
                  <li class="<%= 'active' if params[:category] == category.name %>"> 
                    <%= link_to category.name, destinations_path(category: category.name), class: "link" %>
                  </li>
                <% end %>
              </ul>
          </li>
          
        </ul>
  
      </div>

    </nav> 
    
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/ratings/_form.html.erb
<%= simple_form_for ([@destination, @destination.ratings.build]) do |f| %>
    <div id="rating-form">
        <%= f.input :rating %>        
    </div>

    <%= f.input :comment %>
    <%= f.button :submit %>     
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/'	    
		scoreName: 'review[rating]'
	});
</script>

app/views/ratings/_rating.html.erb
<div class="rating-rating" data-score="<%= rating.rating %>"></div>

<p><%= rating.comment %></p>
<% if redactor_signed_in? %>
    <% if rating.redactor_id == current_redactor.id %>
        <%= link_to "Edit", edit_destination_rating_path(rating.destination, rating) %>
        <%= link_to "Delete", destination_rating_path(rating.destination, rating), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
<% end %>    

app/views/ratings/edit.html.erb
<h1>Edit Rating</h1>

<%= simple_form_for([@destination, @rating]) do |f| %>
    <div id="rating-form">
        <%= f.input :rating %>        
    </div>
    <%= f.input :comment %>
    <%= f.button :submit %>     
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/'	    
		scoreName: 'review[rating]'
	});
</script>

app/views/ratings/new.html.erb
<h1>Add Rating</h1>

<%= render 'form' %>